CircleCI-Public/circleci-yaml-language-server

- pkg/parser/validate/commands.go
When a commend is used only in pre-steps or post-steps, it is marked as unused with a warning diagnostic.
Fixed this issue.
CCI docs on pre- & post-steps: https://circleci.com/docs/configuration-reference/#pre-steps-and-post-steps
> fix: post- and pre-steps are now detected as used

- editors/vscode/yarn.lock
- go.mod
- pkg/parser/dockerImageParser.go
- pkg/parser/dockerImageParser_test.go
- pkg/parser/validate/dockerImage.go
- pkg/services/testdata/noErrors.yml
https://circleci.atlassian.net/browse/DEVEX-1001
When the tag to a Docker image was just a parameter, the tag was silently coerced to `latest`. This led to an ambiguity in the diagnostic: "Docker image ... has no tag latest" (as the user did not specified `latest` anywhere).
This PR removes the coercion and leaves the identification of the parameter to the validation package.
E.g.
```yaml
run_acceptance_tests:
parameters:
go_version:
type: string
docker:
- image: cimg/go:<<parameters.go_version>>
```
> fix: don't coerce docker image tags from parameters to latest

- pkg/services/testdata/noErrors.yml
- schema.json
Allowing OIDC authentication for docker `aws_auth`
This just needed to be put in the validation `schema.json`
https://circleci.atlassian.net/browse/DEVEX-1092
> fix: Allow aws_auth to be given with oidc_role_arn

- pkg/parser/validate/jobs.go
- pkg/parser/validate/jobs_test.go
This PR fixes the range reported for a diagnostic, when a job executor was specified using a parameter, and the parameter's default value did not resolve to an actual job name.
The original code passed a default range instead of the actual executor range to the job checking function.
Before:
After:
> fix: change diagnostic location for param executor default value

- .vscode/launch.json
This PR changes the way the "Attach to Process" debug session is launched in VS Code.
Previously, since `processId` was set to `0`, VS Code let you choose between all processes running on the computer.
By setting `processId` to `"start_server"`, VS Code narrows down the list of processes to attach to to processes named `start_server`, yielding a much shorter list to pick from.
> chore: "attach to process" in VS Code looks for start_server

- .vscode/tasks.json
- Taskfile.yml
This PR adds a task to the `Taskfile` to build the language server with all optimizations disabled. Optimizations made it harder to debug using Delve.
The `build:server:debug` task is used in `tasks.json` to make sure we build the non-optimized version when using VS Code.
> chore: build without optimizations for debug mode

- pkg/utils/machine_images.go
The linux machine images
- https://circleci.com/developer/machine/image/ubuntu-2204
- https://circleci.com/developer/machine/image/ubuntu-2004
have new images released in at the beginning of July (07) https://discuss.circleci.com/t/linux-machine-executor-2023-q3-update/48580
Right now someone following the docs will get a language server error because the latest images are not present in the language server.
So, lets add in these new images
Added the images to the existing arrays
We should no longer see the image value be flagged as `Invalid or deprecated image`
```
jobs:
test_job:
machine:
image: ubuntu-2204:2023.07.2
resource_class: medium
steps:
- checkout
```
> Add July 2023 LinuxVM machine images as valid images

- pkg/parser/validate/executor.go
- pkg/parser/validate/executor_test.go
- pkg/services/complete_test.go
- publicschema.json
macos large and medium resource class are deprecated
remove it from auto complete
flag it as error when used in config files 
remove resource classes from list of mac os resourceclass
open a config file and try this config : 
`version: 2.1
executors:
macos-ios-executor:
macos:
xcode: "13.2.1"
resource_class: large`
> fix: deperecate macos resource class

- pkg/parser/validate/parameters.go
- pkg/parser/validate/parameters_test.go
- pkg/parser/validate/testdata/correct_param_type.yml
- pkg/parser/validate/testdata/wrong_param_type.yml
- pkg/parser/validate/testdata/wrong_param_type_boolean.yml
- pkg/parser/validate/testdata/wrong_param_type_integer.yml
When Parameter is a boolean, the LS flags it as an error when passed to a job that is  expecting a boolean parameter
When the passed parameter refer to global parameter, check the global parameter type  
Check tests
and test this config file 
```
version: 2.1 # Use version 2.1 to enable Orb usage.
parameters:
skipUnitTests:
description: if set to true will not build the c++ unit tests
type: boolean
default: false
jobs:
build:
parameters:
skip:
type: boolean
default: false
docker:
- image: cimg/base:edge
steps:
- checkout
- run: echo "This was triggered by << pipeline.trigger_source >>"
workflows:
commit:
jobs:
- build:
skip: << pipeline.parameters.skipUnitTests >>
```
> fix: parameter flagged due type mismatch even it shouldnt

- pkg/parser/yamlparser.go
- pkg/parser/yamlparser_test.go
- pkg/server/methods/textDocumentSymbols.go
- pkg/services/documentSymbols.go
add IsCacheMissingError to yamlparser
[Jira](https://circleci.atlassian.net/browse/DEVEX-1321)
This PR adds a fallback to the method DocumentSymbols in order to try to parse the file referenced by the uri from the filesystem if parsing from the cache failed.
> feat: DocumentSymbols also parse file from fs if cache failed

- .circleci/config.yml
Only build macOS arm64 binary in build macOS arm64 job.
Following a copy-paste malfunction, the "build macOS x86_64" job built both x86_64 and arm64 architectures.
This PR fixes the config file.
The CI should run without errors after merging on main.
> ci: only build macOS arm64 once

- e2e/__snapshots__/documentSymbol.test.ts.snap
- e2e/completion.test.ts
- e2e/documentSymbol.test.ts
- e2e/utils/commands.ts
- e2e/utils/types.ts
- pkg/parser/yamlparser.go
- pkg/parser/yamlparser_test.go
- pkg/services/documentSymbols/setup.go
- pkg/services/documentSymbols/symbols.go
- test-files/.circleci/continuation.yml
[Jira](https://circleci.atlassian.net/browse/DEVEX-1376)
`textDocument/documentSymbol` also returns the `setup` key.
Add the `setup` information in the `YamlDocument` and use it in `documentSymbol`.
In a config file, write `setup: true` at the top level and make sure you see it in the outline. Put any other value for `setup` and make sure the `setup` do not change.
> feat: add setup true in the returned outline of the ls

- pkg/services/documentSymbols.go
[Jira](https://circleci.atlassian.net/browse/DEVEX-1325)
When the LS receives a `documentSymbols` request, and the file does not exist, return an error to the client.
When the server receives a `documentSymbols` request, it checks that the file exists. If not, it returns an error, optionally removing the file from the cache.
There is also a small helper function that wraps `URI.Filename`, so that it recovers from a possible panic and returns an error instead.
> feat: documentSymbols returns an error if file does not exist

- pkg/services/documentSymbols.go
Jira ticket: None
Because `FileCache` is actually not a cache but holding the state of the VSCode buffer, we must **not** delete the file in the `FileCache` when the cache does not exist on disk.
This reverts commit 5541d4a4c2ae38c04af75beec8ddc72ccc7397d7.
> fix: do not remove files that do not exist on disk from `FileCache`

- .circleci/config.yml
Our ci currently uses an outdated version of `gh` and a lot of flags and commands we use for releasing are not available.
This PR forces the orb `circleci/github-cli` to install the currently latest github cli version `2.37.0`.
> ci: upgrade gh cli to 2.37.0

- pkg/parser/validate/orb.go
- pkg/parser/validate/orb_test.go
- pkg/parser/validate/steps.go
- pkg/parser/validate/testdata/orb_steps_used_in_params.yml
Jira ticket: none
Addresses https://github.com/CircleCI-Public/circleci-yaml-language-server/issues/218. The issue is that when orb commands are used in a job `steps` parameters, we still consider the orb as unused.
Loop over jobs parameters to see if their parameters use the orb.
You can open a file that reproduce the situation in `pkg/parser/validate/testdata/orb_steps_used_in_params.yml` and make sure you get no warning.
> fix: detect orb used in job parameters

- pkg/parser/validate/executor.go
add support for xcode version 15.0.0
update list of xcode versions
test a config file with xcode version 15.0.0
```
version: 2.1
executors:
mac:
macos:
xcode: 15.0.0
environment:
CGO_ENABLED: 0
HOMEBREW_NO_AUTO_UPDATE: 1
TERM: xterm-256color
> fix: add support for xcode version 15.0.0

- .circleci/config.yml
- Taskfile.yml
- scripts/get_next_release.go
- scripts/ldflags.sh
Jira ticket: None
The different workflows used are now split into several workflows. The release and the prerelease happen in different workflows.
There is now workflows just for the feature PRs and workflows just for the release PRs. Amongst the release PR workflows, one of them does the pre-release and one of them does the release.
The workflows are filtered with the `when` instruction at the workflow level.
Most of it will have to be validated on the next release.
> ci: split the workflows

- pkg/parser/validate/parameters.go
False “parameter must be a string” error when passing an enum
Avoid creating an error when passed parameter type is enum and definition is string
test config file 
```
version: 2.1
orbs:
android: circleci/android@2.3.0
commands:
stringeater-choking-on-enums:
parameters:
string-parameter:
type: string
steps:
- run: echo "do nothing"
jobs:
parametric-job:
resource_class: large
docker:
- image: cimg/android:2021.12.2-node
parameters:
enum-parameter:
type: enum
default: apple
enum:
- apple
- orange
steps:
- store_artifacts:
path: << parameters.enum-parameter >>
- stringeater-choking-on-enums:
string-parameter: << parameters.enum-parameter >>
- stringeater-choking-on-enums:
string-parameter: << parameters.enum-parameter >> ""
- …
```
> fix: error when passing an enum to a string param

- pkg/services/diagnostics.go
[Jira](https://circleci.atlassian.net/jira/software/c/projects/DEVEX/issues/DEVEX-1274)
Send Diagnostics when config is not parsed
Don't send empty diagnostics when yaml version is 0
test a config file attached to the ticket
> fix: send diagnostics when config couldn't be parsed

- pkg/parser/validate/executor.go
[Jira](https://circleci.atlassian.net/browse/DEVEX-1554)
Resource classes `windows.medium` and `windows.large` do not exist in our schema / validator
Add missing resources
test config file attached to the ticket
> fix: resource classes windows medium and windows large do not exist in our schema validator

- pkg/ast/orb.go
- pkg/parser/local_orb.go
- pkg/parser/yamlparser.go
- pkg/services/definition_test.go
Jira: None
Go to definition in local orb, targeting other local orb elements was opening a folder instead of making the `Go to definition`.
The issue is actually that local orbs don't know which `yaml` they're coming from, so when asked for definition, they give `<empty string>` and the editor thus try opening the actual directory.
To fix that, the `URI` field has been added to local orbs and it is passed when making `Go to definition`.
Tests have been added but you can try this yourself by declaring a local orb with executor(s), command(s) and job(s). Have jobs use the local orb's executors or commands and try making go to definition on those to make sure it point to the right point.
> fix: go to definition for local orbs were not working

- ADD_A_CLIENT.md
- README.md
[Jira](https://circleci.atlassian.net/browse/LIFE-150)
Adds a doc detailing the specifics about implementing a client for the Language Server.
Prettier messed the README a bit so the PR is split in 2 commits: one to prettier the README and one to update the doc. You may want to look into the second commit only.
Read the doc.
> docs: add documentation on implementing clients

- .circleci/config.yml
This PR updates Go version for macOS build to 1.22.3
Install Go using the Go orb.
> fix: update go version for macOS build

- pkg/ast/workflow.go
- pkg/parser/validate/workflow.go
- pkg/parser/workflows.go
- pkg/parser/workflows_test.go
- pkg/services/definition/workflows.go
- pkg/services/diagnostics_test.go
- pkg/services/testdata/requiresNoErrors.yml
- schema.json
[Jira](https://circleci.atlassian.net/browse/PIPE-4895)
This changes the schema of the `requires` stanza in order to support the flexible requires feature. This will provide customers the ability to define a job's dependencies along with the statuses the dependency must have , in order for the job to start.
This is an example config that demonstrates the new syntax:
```yaml
jobs:
- a
- b
- c:
requires:
- a
- b:
- success
- failed
- d:
requires:
- b: canceled
```
- Update the schema.json to extend the schema of the `requires` stanza
- Update the `parseSingleJobRequires` to handle the new schema
- Update tests
Unit tests
> feat: extend the schema of the requires stanza

- .circleci/config.yml
- .github/workflows/main.yml
[Jira](https://circleci.atlassian.net/browse/LIFE-1129)
- Removes the Feature PR workflow and the Security Scan job (on release branches)
These workflows/jobs require the use of the devex-release context, which is only available to CCI employees. In order to enable external contributions, I've refactored the config so that the context isn't required until build time.
EDIT: I have replaced the `Lint PR title` with a github action as recommended below. This won't run against this PR, only on subsequent ones. 
Not entirely sure about this yet. I think after this is merged, I'm going to have to create a separate github account to test a commit and see if it makes it to CI.
> chore: remove feature PR workflow

- pkg/utils/executors.go
This PR adds a new windows 2022 server image for CUDA
- https://circleci.com/developer/machine/image/windows-server-2022-cuda
Added new image to existing array of images
Here’s a quick usage example:
```
version: 2.1
jobs:
build:
machine:
image: 'windows-server-2019-cuda:edge'
resource_class: windows.gpu.nvidia.medium
shell: powershell.exe -ExecutionPolicy Bypass
steps:
- run: Write-Host 'Hello, Windows'
```
> chore(server): Add new Windows 2022 Nvidia image

- pkg/ast/workflow.go
- pkg/parser/validate/workflow_test.go
- pkg/parser/workflows.go
- pkg/parser/workflows_test.go
- pkg/services/testdata/noErrors.yml
- schema.json
[Jira](https://circleci.atlassian.net/browse/PIPE-5084)
Serial groups are groups of jobs that run in series, this is a new property that can be set for any job type.
For example, creating multiple pipelines at the same time with the below config will result in all pipelines running `test` and `build` but only a single pipeline will run `deploy` at a time.
```yaml
version: 2.1
jobs:
test:
type: no-op
build:
type: no-op
deploy:
type: no-op
workflows:
main-workflow:
jobs:
- test
- build
- deploy:
serial-group: << pipeline.project.slug >>/deploy-group
requires:
- test
- build
```
Serial group keys when compiled:
- Are optional and defined on the job invocation.
- Must be a non-empty string fewer than 512 characters.
Note: this is after compilation, limiting what we can validate here, this …
> feat: PIPE-5084 Update job references to support serial groups

- pkg/parser/validate/steps.go
- pkg/services/background_auto_rerun_test.go
- publicschema.json
[Jira](https://circleci.atlassian.net/browse/PIPE-5246)
Add validation for step rerun fields: 
- `max_auto_reruns` - value is between 1 and 5
- `auto_rerun_delay` - value should be in a duration format, not longer than 10 minutes, and should conform to `(10|[1-9])m|([1-9][0-9]*)s` regex (be in the form of either minutes or seconds)
unit tests
> feat: add validation for values of step rerun fields

- HACKING.md
- pkg/ast/job.go
- pkg/parser/jobs.go
- pkg/parser/jsonschema_test.go
- pkg/parser/validate/jobs.go
- pkg/parser/validate/jobs_test.go
- pkg/services/complete/jobs.go
- pkg/services/complete_test.go
- pkg/utils/jobs.go
- publicschema.json
- schema.json
Jira: https://circleci.atlassian.net/browse/PIPE-5266
This PR adds support for two job types:
- `lock`
- `unlock`
While these job types are not explicitly explained in the docs, they are the underling job types that our [serial group](https://circleci.com/docs/guides/orchestrate/controlling-serial-execution-across-your-organization/) feature uses under the hood.
This MR also also adds improved validations for other job types that we already had:
- `approval` / `no-op` jobs don't need any additional parameters to be valid
- `lock` / `unlock` require a `key: ` parameter to be specified
```yml
my-cool-lock-job:
type: lock
```
- <img width="585" height="361" alt="image" src="https://github.com/user-attachments/assets/d9d664dc-c9f2-4b39-8928-07556cc9eca5" />
- `release` jobs require a …
> feat: Add lock jobs and improve job JSON schema validations
