- pkg/services/semantics.go
check docker and executor steps too!
> fix "docker" keyword colour anomaly

- pkg/parser/validate/executor.go
- pkg/services/complete_test.go
https://circleci.com/developer/machine/image/ubuntu-2004
https://circleci.com/developer/machine/image/ubuntu-2204
> fix: updated supported ubuntu images

- .circleci/config.yml
Updates to the vulnerability scanning on the project. Now using Snyk and a low-privileged account to only scan and upload results.
> Update vulnerability scanning

- e2e/__snapshots__/diagnostic.test.ts.snap
- e2e/diagnostic.test.ts
- pkg/parser/steps.go
- test-files/.circleci/matrix-alias.yml
- test-files/.circleci/parameter-inline.yml
https://github.com/CircleCI-Public/circleci-yaml-language-server/pull/74#issuecomment-1401807187
> Fix: fixed invalid syntax validation for parameter entered in-line

- pkg/ast/orb.go
- pkg/parser/orbs.go
- pkg/parser/orbs_test.go
- pkg/services/complete/orb_cache.go
- pkg/services/complete/orbs.go
How to test: put your cursor anywhere on an orb version to get autocompletion
Put your cursor anywhere else on the orb to make the standard orb completion is not affected
> DEVEX-307: add autocompletion on orb version

- e2e/__snapshots__/diagnostic.test.ts.snap
- pkg/parser/yamlparser.go
- pkg/services/semantics.go
should test on any orb method:
- see that before orb methods were not highlighted
- now they are
> fix: Fix semantics not working on orbs

- .circleci/config.yml
- pkg/parser/validate/executor_test.go
- pkg/parser/validate/orb.go
- pkg/parser/validate/steps.go
- pkg/parser/validate/steps_test.go
- pkg/parser/validate/workflow.go
- pkg/parser/validate/workflow_test.go
- pkg/parser/yamlparser.go
- pkg/parser/yamlparser_test.go
- pkg/services/testdata/noErrors.yml
https://circleci.atlassian.net/browse/DEVEX-1000
> fix: Do not raise error when the orb can not be downloaded

- pkg/parser/jobs.go
- pkg/parser/jobs_test.go
- pkg/parser/validate/executor.go
- pkg/parser/validate/jobs.go
- pkg/parser/validate/jobs_test.go
- pkg/services/complete_test.go
This PR ensures validation of `resource_class` in job definitions.
> feat: validate resource_class in job definition

- cmd/start_server/start_server.go
- pkg/dockerhub/exists.go
- pkg/dockerhub/repositories.go
- pkg/dockerhub/tags.go
- pkg/server/methods/initialize.go
- pkg/server/methods/resourceClass.go
- pkg/server/methods/rollbar.go
- pkg/server/methods/telemetry.go
- pkg/server/server.go
- pkg/utils/buildVars.go
- pkg/utils/git.go
- pkg/utils/gqlclient.go
- pkg/utils/lsContext.go
- pkg/utils/project.go
- pkg/utils/userAgent.go
- scripts/ldflags.sh
[Jira](https://circleci.atlassian.net/browse/DEVEX-1258)
Add user agent to all API calls, and add LS version to user agent
> fix: add user agent and version

- pkg/server/methods/initialize.go
[Jira](https://circleci.atlassian.net/browse/DEVEX-1258)
In order to give even more details to our API requests, add the opportunity to extend user agent from initializing process
> fix: add spawning process user agent

- pkg/parser/validate/jobs.go
- pkg/parser/validate/jobs_test.go
[Jira](https://circleci.atlassian.net/browse/DEVEX-1088)
This PR adds a warning message when a parameter without default value is used as an executor value.
This PR does not remove the error for unknown executor.
unit test
> feat: [DEVEX-1088] add warn when executor param has no default value

- .circleci/config.yml
- .circleci/release/release-please-config.json
- .eslintignore
- .prettierrc.js
- commitlint.config.js
- package.json
- yarn.lock
[Jira](https://circleci.atlassian.net/browse/DEVEX-1278)
This PR reconfigures the CI to work for trunk-base development centered on `main`.
The main details are explained in the [Next Steps section of the tunk-based initiative.](https://circleci.atlassian.net/wiki/spaces/DE/pages/6933741613/Moving+our+repositories+to+trunk-based+development#Next-steps)
> ci: change config for trunk-based workflow

- .circleci/config.yml
Jira ticket: None
Now on every release push to master, after the pre-release and the release-please jobs, the upload artifacts look if the last release is in draft. If it is in draft, it uploads the artefacts and undraft the release.
We'll validate on next release
> chore: fix release process

- e2e/diagnostic.test.ts
> ci: update test timeout

- .circleci/config.yml
> ci: add checkout step to release

- .circleci/config.yml
> fix: release is now in 2 steps

- .circleci/config.yml
> fix: forcing release undraft on tag

- .circleci/config.yml
Jira: none
Add context for snyk CI jobs
> ci: fix snyk issue

- .circleci/config.yml
> fix: fix release process

- pkg/utils/machine_images.go
[Jira](https://circleci.atlassian.net/browse/DEVEX-1564)
Add missing images
> fix: valid images

- .circleci/config.yml
- scripts/ldflags.sh
[Jira](https://circleci.atlassian.net/browse/DEVEX-1552)
> fix: build binary using static linking

- pkg/utils/machine_images.go
Jira: None
Add the last ubuntu version supported by CircleCI
Thanks to @mxa0079 for proposing this change in https://github.com/CircleCI-Public/circleci-yaml-language-server/pull/282
> feat: add latest ubuntu versions

- pkg/utils/machine_images.go
[Jira](https://circleci.atlassian.net/browse/LIFE-297)
support new ubuntu machine version
> fix: update ubuntu version

- pkg/parser/validate/executor.go
- pkg/parser/validate/jobs_test.go
- pkg/utils/executors.go
- publicschema.json
Replacement for #297 to get around failing status checks. The check that was failing was trying to assign the PR to someone who is no longer here.
> fix: remove deprecated class

- pkg/utils/executors.go
[LIFE-794](https://circleci.atlassian.net/browse/LIFE-794)
Support new ubuntu machine version.
[LIFE-794]: https://circleci.atlassian.net/browse/LIFE-794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: update to current ubuntu version

- pkg/utils/executors.go
[Jira](https://circleci.atlassian.net/browse/LIFE-450)
Add Ubuntu 2024 images
> feat: [LIFE-450] Update Ubuntu images

- pkg/utils/executors.go
This PR adds new linux images for q4
- https://circleci.com/developer/machine/image/android
Added new image to existing array of images
Here’s a quick usage example:
```
version: 2.1
workflows:
main:
jobs:
- build
jobs:
build:
machine:
image: android:2024.11.1
steps:
- checkout
- run: echo "Hello, world!"
```
> chore(server): update q4 android images

- pkg/utils/executors.go
This PR adds new windows 2019 images for q4
- https://circleci.com/developer/machine/image/windows-server-2019
Added new image to existing array of images
Here’s a quick usage example:
```
version: 2.1
jobs:
build:
machine:
image: 'windows-server-2019-vs2019:2024.12.1'
resource_class: windows.medium
shell: powershell.exe -ExecutionPolicy Bypass
steps:
- run: Write-Host 'Hello, Windows'
```
> chore(server): update q4 windows 2019 image

- pkg/utils/executors.go
This PR adds new windows 2022 images for q4
- https://circleci.com/developer/machine/image/windows-server-2022-gui
Added new image to existing array of images
Here’s a quick usage example:
```
version: 2.1
jobs:
build:
machine:
image: 'windows-server-2022-gui:2024.12.1'
resource_class: windows.medium
shell: powershell.exe -ExecutionPolicy Bypass
steps:
- run: Write-Host 'Hello, Windows'
```
> chore(server): update q4 windows 2022 image

- pkg/utils/executors.go
https://github.com/CircleCI-Public/circleci-yaml-language-server/issues/331
Adds latest XCode versions, I also double checked the mac resource classes and added some that were missing
> chore: add support for latest xcode versions

- pkg/utils/executors.go
No ticket
Adds new Xcode versions
https://circleci.com/changelog/xcode-16-4-rc-available/
> chore: add Xcode versions 16.3.0 and 16.4.0

- pkg/server/methods/envVariables.go
- pkg/utils/context.go
I've made sure this all works end to end
> chore: use public API for getting context env vars

- .github/pull_request_template.md
- README.md
this is important info that hasn't been documented anywhere.
> chore: specify release-please instructions

- README.md
My previous PR didn't release, because it was marked as a `chore`.
> feat: make a release

- pkg/parser/validate/workflow.go
- pkg/server/methods/envVariables.go
- pkg/services/complete/steps.go
- pkg/utils/context.go
- workflow was incorrectly looking up org by name, instead of ID
- also tweak the contexts query to populate the cache as it paginates, instead of waiting to the end
> fix: environment variable lookup

- pkg/ast/step.go
- pkg/parser/steps.go
- pkg/parser/validate/steps.go
- pkg/parser/validate/steps_test.go
- pkg/parser/validate/testdata/invalid_checkout_method.yml
- pkg/parser/validate/testdata/valid_checkout_method.yml
- publicschema.json
Jira: https://circleci.atlassian.net/browse/EXEC-5709
**Important note** : Release-please will only create a release PR for releases with a `feat` or `fix` commit message. If your PR starts with `chore` , your changes will NOT be released.
Add method to the checkout step fields. It can be one of 'blobless' or 'full'.
Adds a new validation function specific to validating checkout fields.
`task test`
> feat: add method to checkout step fields
